name: Auto Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "ampundeejay"
          git config --global user.email "fadilreza@icloud.com"

      - name: Update log file
        run: |
          echo "Auto commit on $(date)" >> log.txt
          git add log.txt
          git commit -m "Auto commit on $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
